import defaultTheme from 'tailwindcss/defaultTheme'

export default {
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'surface-dim': '#dadada',
                error: '#ba1a1a',
                'primary-fixed-dim': '#aed500',
                'on-tertiary-fixed': '#1b1c1c',
                'tertiary-container': '#efeded',
                'on-secondary-container': '#646464',
                'surface-container': '#eeeeee',
                'on-secondary': '#ffffff',
                'on-secondary-fixed': '#1b1b1b',
                'on-error': '#ffffff',
                secondary: '#5e5e5e',
                'inverse-surface': '#2f3131',
                'surface-container-low': '#f3f3f3',
                'tertiary-fixed-dim': '#c7c6c6',
                'on-tertiary': '#ffffff',
                primary: '#526600',
                'on-tertiary-fixed-variant': '#464747',
                'tertiary-fixed': '#e4e2e2',
                'secondary-container': '#e2e2e2',
                'surface-bright': '#f9f9f9',
                surface: '#f9f9f9',
                'on-error-container': '#93000a',
                'on-primary-fixed': '#171e00',
                'inverse-primary': '#aed500',
                'secondary-fixed-dim': '#c6c6c6',
                'inverse-on-surface': '#f1f1f1',
                'surface-container-highest': '#e2e2e2',
                'on-primary-container': '#5d7300',
                'outline-variant': '#c4c9ac',
                tertiary: '#5e5e5e',
                'secondary-fixed': '#e2e2e2',
                'surface-container-high': '#e8e8e8',
                'surface-container-lowest': '#ffffff',
                'on-secondary-fixed-variant': '#474747',
                'on-tertiary-container': '#6b6b6b',
                background: '#f9f9f9',
                'primary-fixed': '#c6f300',
                'primary-container': '#d0ff00',
                'on-primary': '#ffffff',
                'on-background': '#1a1c1c',
                'surface-tint': '#526600',
                'on-surface': '#1a1c1c',
                'surface-variant': '#e2e2e2',
                'on-primary-fixed-variant': '#3d4d00',
                'on-surface-variant': '#444933',
                'error-container': '#ffdad6',
                outline: '#757a60',

                // Old colors for backward compatibility if needed, but we should prioritize new ones
                washi: '#f7f5f0',
                sumi: '#1a1a1a',
                matcha: '#7c8c5a',
                hai: '#888888',
                usuzumi: '#b4b4b4',
                usuzemi: '#5a6b6a',
                kuro: '#0a0a0a',
                take: '#4a9d6f',
                sakura: '#d97781',
                shironeri: '#fefcf8',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                gutter: '24px',
                unit: '8px',
                'max-width': '1440px',
                margin: '64px',
            },
            fontFamily: {
                body: ['Inter', ...defaultTheme.fontFamily.sans],
                heading: ['Lexend', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Lexend'],
                'label-bold': ['Lexend'],
                'headline-md': ['Lexend'],
                'body-lg': ['Inter'],
                'label-mono': ['Inter'],
                'headline-xl': ['Lexend'],
                'body-md': ['Inter'],
            },
        },
    },
}
